/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
//typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
//typedef float _Complex GoComplex64;
//typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


extern char* GetPCID();

extern GoInt64 StringToStamp(char* p0);

extern char* StampToString(GoInt64 p0);

extern char* Sign(char* p0, GoInt64 p1);

extern GoUint8 Verify(char* p0);

extern GoInt64 ReadLimit(char* p0);

extern char* ReadPCID(char* p0);

extern char* ReadSig(char* p0);

extern char* InviteCode(GoInt64 p0, GoInt64 p1);

extern GoInt64 InvitePhone(char* p0);

extern GoInt64 InviteIndex(char* p0);

extern char* GetUserCode(char* p0);

extern char* UpdateUserCode(char* p0, GoInt64 p1);

extern char* SignUserCode(char* p0);

extern GoUint8 VerifyUserCode(char* p0);

extern GoInt64 GetLimit(char* p0);

extern char* GetCPU(char* p0);

extern GoInt64 GetPhoneNum(char* p0);

extern GoInt64 GetIndex(char* p0);

#ifdef __cplusplus
}
#endif
